config/routes.rb
Tea::Application.routes.draw do  
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout' 
 
  root :to => 'wanteds#index'
  resources :wanteds
  resources :people

  get "welcome/say_hello" => "welcome#say"
  get "welcome" => "welcome#index"
  

  root :to => 'welcome#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  attr_accessible :bio, :birthday, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.firstname = auth.info.first_name
      user.lastname = auth.info.last_name
      user.image = auth.info.image
      user.email = auth.info.email
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/models/wanted.rb
class Wanted < ActiveRecord::Base
  attr_accessible :msg, :date, :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  # GET /people
  # GET /people.json
  def index
    @people = Person.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @people }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @person = Person.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/new
  # GET /people/new.json
  def new
    @person = Person.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @person }
    end
  end

  # GET /people/1/edit
  def edit
    @person = Person.find(params[:id])
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(params[:person])

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render json: @person, status: :created, location: @person }
      else
        format.html { render action: "new" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /people/1
  # PUT /people/1.json
  def update
    @person = Person.find(params[:id])

    respond_to do |format|
      if @person.update_attributes(params[:person])
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/wanteds_controller.rb
class WantedsController < ApplicationController
  # GET /wanteds
  # GET /wanteds.json
  def index
    @wanteds = Wanted.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @wanteds }
    end
  end

  # GET /wanteds/1
  # GET /wanteds/1.json
  def show
    @wanted = Wanted.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wanted }
    end
  end

  # GET /wanteds/new
  # GET /wanteds/new.json
  def new
    @wanted = Wanted.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wanted }
    end
  end

  # GET /wanteds/1/edit
  def edit
    @wanted = Wanted.find(params[:id])
  end

  # POST /wanteds
  # POST /wanteds.json
  def create
    @wanted = Wanted.new(params[:wanted])

    respond_to do |format|
      if @wanted.save
        format.html { redirect_to @wanted, notice: 'Wanted was successfully created.' }
        format.json { render json: @wanted, status: :created, location: @wanted }
      else
        format.html { render action: "new" }
        format.json { render json: @wanted.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /wanteds/1
  # PUT /wanteds/1.json
  def update
    @wanted = Wanted.find(params[:id])

    respond_to do |format|
      if @wanted.update_attributes(params[:wanted])
        format.html { redirect_to @wanted, notice: 'Wanted was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wanted.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wanteds/1
  # DELETE /wanteds/1.json
  def destroy
    @wanted = Wanted.find(params[:id])
    @wanted.destroy

    respond_to do |format|
      format.html { redirect_to wanteds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def say
    end

    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tea</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Beauty Tea
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    #user_nav
      - if current_user
        Welcome, 
        %strong= current_user.name 
        = image_tag current_user.image
        = link_to "Sign out", signout_path, id: "sign_out" 
        !
      - else
        = link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" 
    
    
    = yield 

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Bio</th>
    <th>Birthday</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @people.each do |person| %>
  <tr>
    <td><%= person.name %></td>
    <td><%= person.bio %></td>
    <td><%= person.birthday %></td>
    <td><%= link_to 'Show', person %></td>
    <td><%= link_to 'Edit', edit_person_path(person) %></td>
    <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @person.name %>
</p>

<p>
  <b>Bio:</b>
  <%= @person.bio %>
</p>

<p>
  <b>Birthday:</b>
  <%= @person.birthday %>
</p>


<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/wanteds/_form.html.erb
<%= form_for(@wanted) do |f| %>
  <% if @wanted.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wanted.errors.count, "error") %> prohibited this wanted from being saved:</h2>

      <ul>
      <% @wanted.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :msg %><br />
    <%= f.text_area :msg %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wanteds/_form.html.haml
= form_for(@wanted) do |f|
  - if @wanted.errors.any?
    #error_explanation
      %h2
        = pluralize(@wanted.errors.count, "error")
        prohibited this wanted from being saved:
      %ul
        - @wanted.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :msg
    %br/
    = f.text_area :msg
  .field
    = f.label :date
    %br/
    = f.date_select :date
  .actions
    = f.submit

app/views/wanteds/edit.html.erb
<h1>Editing wanted</h1>

<%= render 'form' %>

<%= link_to 'Show', @wanted %> |
<%= link_to 'Back', wanteds_path %>

app/views/wanteds/edit.html.haml
%h1 Editing wanted
= render 'form'
= link_to 'Show', @wanted
|
\#{link_to 'Back', wanteds_path}

app/views/wanteds/index.html.erb
<h1>Listing Posts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Msg</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @wanteds.each do |wanted| %>
  <tr>
    <td><%= wanted.name %></td>
    <td><%= wanted.msg %></td>
    <td><%= wanted.date %></td>
    <td><%= link_to 'Show', wanted %></td>
    <td><%= link_to 'Edit', edit_wanted_path(wanted) %></td>
    <td><%= link_to 'Destroy', wanted, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_wanted_path %>

app/views/wanteds/index.html.haml
%h1 Listing Wanteds

%table#wanteds
  %thead
    %tr
      %th Name 
      %th Message
      %th Date
      %th 
      %th 
      %th 
  
  %tbody
    - @wanteds.each do |wanted|
      %tr
        %td= wanted.name
        %td= wanted.msg
        %td= wanted.date
        %td= link_to 'Show', wanted
        %td= link_to 'Edit', edit_wanted_path(wanted)
        %td= link_to 'Destroy', wanted, method: :delete, data: { confirm: 'Are you sure?' } 
  

=link_to 'New Wanted', new_wanted_path

app/views/wanteds/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', wanteds_path %>

app/views/wanteds/new.html.haml
%h1 New Wanted

= render :partial => 'form' 

= link_to 'Back', wanteds_path

app/views/wanteds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @wanted.name %>
</p>

<p>
  <b>Msg:</b>
  <%= @wanted.msg %>
</p>

<p>
  <b>Date:</b>
  <%= @wanted.date %>
</p>


<%= link_to 'Edit', edit_wanted_path(@wanted) %> |
<%= link_to 'Back', wanteds_path %>

app/views/wanteds/show.html.haml
%p
  %b Name:
  = @wanted.name

%p
  %b Msg:
  = @wanted.msg 

%p
  %b Date:
  = @wanted.date 

= link_to 'Edit', edit_wanted_path(@wanted)  
|
\#{link_to 'Back', wanteds_path} 

app/views/welcome/index.html.erb
<p>Yo! It's <%= Time.now %></p>
<p><%= link_to 'HR', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>HR Service Website</h1>
<p><%= link_to "Home", root_path %></p>